Added alfred-telemetry-solr providing prometheus metrics for solr
xenit-eu/alfred-telemetry pull request #32
Opened 2020-10-29 14:57 UTC by tgeens

New PR to add the alfred-telemetry-solr prometheus metrics.

commits have been squashed, is that ok for you ?

2020-10-29 16:05 UTC, anghelutar requested changes
In README: integration tests should be run via ./gradlew integrationTest

2020-10-29 19:56 UTC, anghelutar approved these changes

2020-10-30 07:55 UTC, tgeens commented
Thanks for fixing it :+1:

2020-10-30 09:00 UTC, anghelutar approved these changes

2020-10-30 09:53 UTC, anghelutar approved these changes

2020-10-30 10:05 UTC, merged