SOLR-DISABLE-FLOC-ID: Added floc-id-enabled property.
xenit-eu/alfred-telemetry pull request #35
Opened 2020-11-03 11:05 UTC by TomVerschuerenXenit

I used a static variable since it isn't easy to obtain the globalProperties. I'm new to Spring and figuring that out would take a while.
This feature will also be removed in the future anyway.

If you believe this is terrible code, please point me in the right direction on how I could get access to globalProperties in SolrShardingMetrics.

2020-11-03 11:14 UTC, thijslemmens requested changes

2020-11-03 11:14 UTC, thijslemmens commented on alfred-telemetry-platform/src/main/java/eu/xenit/alfred/telemetry/binder/solr/sharding/SolrShardingMetrics.java
> +    public static boolean FLOC_ID_ENABLED = true;
No need to make this static. Add it as an optional constructor argument.

2020-11-03 13:50 UTC, thijslemmens submitted a review, later dismissed

2020-11-03 14:27 UTC, tgeens commented
@TomVerschuerenXenit can you also add this new property to the docs ?

2020-11-04 12:51 UTC, tgeens approved these changes

2020-11-04 12:52 UTC, merged